### PR TITLE
feat(hooks): change script prefix to works on windows

### PR DESCRIPTION
**Pull request by ulthuan**
Hi all!,
I was make a little change in the code for do the GIT_ARGS prefix compatible with Windows shell.

I hope this is helpfully :)

Regards,

### CODE REVIEW

**Comment by umbopepato** [comment]
Hi @ulthuan, thank you so much for your PR! 😊 

Making the script prefix dynamic is a good starting point to support more shells for git hooks, although I'm afraid that the OS check alone would not be enough: the `args` variable assignment syntax differs between Powershell and batch. This is essentially the same problem as #73, for which I guess the only solution is to implement a shell detection strategy to select from different prefixes.
For windows users it might be interesting to leverage the bash port which usually comes with git (where hooks are executed), but detecting that specific environment doesn't seem very straightforward nor reliable.

What do you think?

**Comment by ulthuan** [comment]
I understand the problem....

What do you think about use the ppid for get the parent shell process and with this name create a instance of shell class and in this class make a function that return the prefix string with the correct format?

Of course I think that this solution not resolve all the situations but If you launch the vr command on the shell I think that it can works.

**Comment by umbopepato** [comment]
Yeah that should work, but it would require introducing a breaking change in the current shell detection strategy so I'd probably stick to the dynamic git args expression. We could analyze the result of `resolveShell()` to detect the different shells, something like:


https://github.com/jurassiscripts/velociraptor/blob/e5841bae29f02004961732d0d487a9bd4d88296a/src/cli/commands/run_hook.ts#L24-L30

👇 

```typescript
await runScript({
  configData: this.configData!,
  script: script[0],
  prefix: (shell: string) => /* Generate git args prefix depending on the resolved shell.
                                Detect shell type using regexes/endsWith()? */,
  additionalArgs: args,
  argsForwardingMode: ArgsForwardingMode.INDIRECT,
});
```

What do you say? Happy to help you implement this starting from your PR in case.

**Comment by ulthuan** [comment]
Hi @umbopepato,
I uploaded my first try with your suggestions, that I agree with you that it's better to start with this method.

I hope you find it useful.

Sorry for my English.

Regards,

**Pull request merged**
